### ISSUE TITLE
No works in Leaflet 1.3

### ISSUE THREAD

**Issue by VladimirKalachikhin** [ScanEx/L.TileLayer.Mercator#1]
`TypeError: this._getTileSize is not a function[Learn More]  TileLayer.Mercator.js:48:32
	._update http://192.168.10.10/map/Leaflet.TileLayer.Mercator/src/TileLayer.Mercator.js:48:32
	GridLayer<._setView http://192.168.10.10/map/leaflet/leaflet-src.js:10977:5
	GridLayer<._resetView http://192.168.10.10/map/leaflet/leaflet-src.js:10935:3
	GridLayer<.onAdd http://192.168.10.10/map/leaflet/leaflet-src.js:10572:3
	.onAdd http://192.168.10.10/map/Leaflet.TileLayer.Mercator/src/TileLayer.Mercator.js:106:17
	Layer<._layerAdd http://192.168.10.10/map/leaflet/leaflet-src.js:6487:3
	Map<.whenReady http://192.168.10.10/map/leaflet/leaflet-src.js:4367:4
	.addLayer http://192.168.10.10/map/leaflet/leaflet-src.js:6549:3
	Layers<._onInputClick http://192.168.10.10/map/leaflet/leaflet-src.js:5170:5
	addOne/handler http://192.168.10.10/map/leaflet/leaflet-src.js:2280:10`

**Comment by OriginalSin** [comment]
А примерчик есть который не работает?

**Comment by VladimirKalachikhin** [comment]
О! Работает. Оказывается, L.TileLayer.Mercator и Leaflet.TileLayer.Mercator - не одно и то же...
Прошу прощения, перепутал L.TileLayer.Mercator и Leaflet.TileLayer.Mercator, и сообщил об ошибке не туда. Проблема есть в Leaflet.TileLayer.Mercator.

Но L.TileLayer.Mercator работает нормально:
![screenshot at 2018-03-05 20 18 10](https://user-images.githubusercontent.com/32364744/36989338-7f79bd3c-20b2-11e8-9803-b7d927fe4ff5.png)

**Comment by VladimirKalachikhin** [comment]
А можно консультацию для тех, кто слаб в JavaScript?
Как теперь нарисовать тайловую сетку EPSG3395? Или хотя бы получить номер тайла? Ну, идеологически-правильным способом.

**Comment by OriginalSin** [comment]
А код или ссылку на страницу где вы это применяете?
Карта в какой проекции?

**Comment by VladimirKalachikhin** [comment]
Номер тайла нужен как простой способ указания региона для предварительного скачивания в любительском проекте лёгкого тайлового кэш-прокси. Но в рамках этой задачи действительно нет необходимости рисовать правильную сетку тайлов. Достаточно иметь функцию, которая в ответ на компоненты "z" и "y" номера тайла в проекции "Меркатор на сфере" возвращает "у" двух тайлов в проекции "Меркатор на эллипсоиде". И наоборот.

Но я плохо понимаю, как устроена библиотека Leaflet, и почему при, вроде бы, заявленной поддержке проекций, работающим способом показать два слоя в разных проекциях является бесхитростный сдвиг одного из них.

**Comment by OriginalSin** [comment]
А по скайпу можно - sergik1k1

**Comment by VladimirKalachikhin** [comment]
Нет, со скайпом проблемы. Но я вполне готов беседовать по почте: v.kalachikhin@gmail.com

**Comment by OriginalSin** [comment]
Писать про идеологию плагина долго... Если в код плагина заглянуть то видно что это работает просто как сдвиг всех тайлов на экране на одну величину по Y расчитываемый по текущему положению центра экрана...

**Comment by VladimirKalachikhin** [comment]
Ну я в код заглянул, но понял мало.
Собственно, я не понял главного - вот здесь что происходит?:
shift = (map.options.crs.project(pos).y - this.options.tilesCRS.project(pos).y);

**Comment by VladimirKalachikhin** [comment]
Я наконец сообразил, что crs является свойством карты, а не слоя. Соответственно, в Leaflet все слои должны быть в одной проекции.
Если карта в умолчальной проекции EPSG3857, и я рисую тайловую сетку вот таким образом:
```
var tileGrid = new L.GridLayer();
tileGrid.createTile = function (coords) {
	var tile = document.createElement('div');
	tile.style.outline = '1px solid rgba(255,69,0,1)';
	tile.style.fontWeight = 'bold';
	tile.style.fontSize = '24pt';
	tile.style.color = 'rgba(255,69,0,0.75)';
	tile.innerHTML = ' x = '+coords.x+'<br> y = '+coords.y;
	return tile;
}
tileGrid.addTo(map);
```
то для получения сетки тайлов EPSG3395 я должен сдвинуть свою сетку аналогично тому, как это делает Ваш плагин. Но применить Ваш плагин я не могу, потому что он расширяет класс L.TileLayer , а сетку я рисую с помощью его предка L.GridLayer.
Т.е., возможно, было бы правильней, если бы Ваш плагин расширял класс L.GridLayer, потому что все рисуют сетку по примеру из документации.
